"use client";
import React, { useEffect, useState } from "react";
import MovieCont from "@/component/movie/MovieCont";
import ContTitle from "@/component/title/ContTitle";
import MovieSearch from "@/component/movie/MovieSearch";
import MovieTag from "@/component/movie/MovieTag";
import MovieSlider from "@/component/movie/MovieSlider";

export const metadata = {
  title: "Movie API",
  description: "Generated by create Movie API",
};

const Movie = () => {
  const [movies, setMovies] = useState([]);

  const search = async (query) => {
    await fetch(`${query}?api_key=9278d13f704ad0fe53c2263b692efd89`)
      .then((response) => response.json())
      .then((result) => {
        console.log("query:", query);
        console.log("results:", result.results);
        setMovies(result.results);
      })
      .catch((error) => console.log(error));
  };

  useEffect(() => {
    const getData = async () => {
      const res = await fetch(
        "https://api.themoviedb.org/3/movie/popular?api_key=9278d13f704ad0fe53c2263b692efd89"
      );
      if (!res.ok) {
        throw new Error("Failed to fetch data");
      }
      const data = await res.json();
      setMovies(data.results);
    };
    getData();
  }, []);
  // console.log(movies);

  return (
    <>
      <ContTitle title="movie" />
      <MovieSlider movies={movies} />
      <MovieSearch onSearch={search}/>
      <MovieTag onSearch={search} />
      <MovieCont movies={movies} />
    </>
  );
};

export default Movie;
